92,
Finding Likelihoods,
,
Finding Likelihoods,
1,
2020-07-31 15:22,
842,
Albertjvr,
,
0,
0,
,
0,
false,
{"split_page":"0",
"list_view_and_query":"1",
"access":"1",
"intro":"",
"outro":"",
"repeat_group_button":0,
"repeat_template":"repeatgroup",
"repeat_max":"",
"repeat_min":"",
"repeat_num_element":"",
"repeat_error_message":"",
"repeat_no_data_message":"",
"repeat_intro":"",
"repeat_add_access":"1",
"repeat_delete_access":"1",
"repeat_delete_access_user":"",
"repeat_copy_element_values":"0",
"group_columns":"1",
"group_column_widths":"",
"repeat_group_show_first":1,
"random":"0",
"labels_above":"-1",
"labels_above_details":"-1"}
